spring.application.name=medication-tracker-backend
spring.datasource.url=jdbc:mysql://localhost:3306/medication_db
spring.datasource.username=root
spring.datasource.password=anubama@123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=0af1eb83e5e0c16cfb4522b8f480421e05ba45ec81355ce5b1fff276be361440
server.port=8080